name: p2p
channels:
  - plotly
  - pytorch
  - nvidia
  - anaconda
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - antlr-python-runtime=4.9.3
  - appdirs=1.4.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contourpy=1.2.0
  - cryptography=41.0.3
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-runtime=12.1.0
  - cycler=0.12.1
  - cython=3.0.11
  - cytoolz=0.12.2
  - daal4py=2023.2.1
  - dal=2023.2.1
  - dask-core=2024.5.0
  - dbus=1.13.18
  - docker-pycreds=0.4.0
  - expat=2.5.0
  - fastprogress=1.0.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.45.1
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.40
  - glib=2.72.1
  - glib-tools=2.72.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - huggingface_hub=0.20.3
  - hydra-core=1.3.2
  - hydra-submitit-launcher=1.2.0
  - icu=73.2
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20230802.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.1.2
  - libcups=2.3.3
  - libcurand=10.3.4.101
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.72.1
  - libgomp=13.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=4.25.1
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.16
  - libxkbcommon=1.0.3
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lightning-utilities=0.10.0
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=4.1.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.20
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - omegaconf=2.3.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.2.0
  - packaging=23.2
  - pandas=2.1.1
  - partd=1.4.1
  - pathtools=0.1.2
  - pcre=8.45
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=3.10.0
  - plotly=5.19.0
  - ply=3.11
  - progressbar2=4.2.0
  - protobuf=4.25.1
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pycocotools=2.0.8
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-utils=3.3.3
  - python_abi=3.11
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywavelets=1.7.0
  - pyyaml=6.0.1
  - qt-main=5.15.2
  - readline=8.2
  - regex=2023.10.3
  - requests=2.31.0
  - safetensors=0.4.2
  - scikit-image=0.20.0
  - scikit-learn=1.3.2
  - scikit-learn-intelex=2023.2.1
  - scipy=1.11.3
  - seaborn=0.12.2
  - sentry-sdk=1.35.0
  - setproctitle=1.3.3
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - smmap=5.0.0
  - sqlite=3.41.2
  - submitit=1.5.1
  - sympy=1.12
  - tbb=2021.8.0
  - tenacity=8.2.2
  - threadpoolctl=3.2.0
  - tifffile=2020.6.3
  - tk=8.6.13
  - tokenizers=0.15.1
  - tomli=2.0.1
  - toolz=0.12.0
  - torchaudio=2.1.1
  - torchmetrics=1.2.0
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - transformers=4.37.2
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  - wandb=0.16.6
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - bcos==0.1.2
      - docopt==0.6.2
      - einops==0.8.0
      - fast-slic==0.4.0
      - flatbuffers==24.12.23
      - fsspec==2024.3.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - keras==3.7.0
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.13.1
      - pipreqs==0.4.13
      - pygments==2.18.0
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.15.0
      - pytorch-minimize==0.0.2
      - rich==13.9.4
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - yarg==0.1.9
